mod2_binary:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0


mod2_integral:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0

modular_arithmetic:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0

hamming_weight1:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0

hamming_weight_probability:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0

is_prime:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0

mobius:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0

totient:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0
