mod2_binary:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    output_dim: TODO
    lr: 1e-3


mod2_integral:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    output_dim: TODO
    lr: 1e-3

modular_arithmetic:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    output_dim: TODO
    lr: 1e-3

hamming_weight1:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    output_dim: TODO
    lr: 1e-3

hamming_weight_probability:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    output_dim: TODO
    lr: 1e-3

is_prime:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    output_dim: TODO
    lr: 1e-3

mobius:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    output_dim: TODO
    lr: 1e-3

totient:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    output_dim: TODO
    lr: 1e-3


