mod2_binary:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0


mod2_integral:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0

modular_arithmetic:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0

hamming_weight1:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0

hamming_weight_probability:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0

is_prime:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0
    modular_features_N: 100
    output_file: PrimeOrNot_experiment_results.txt

mobius:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: cross_entropy # since predicting -1, 0, 1
    n_hidden: 3
    input_dim: TODO # depends on input_type
    hidden_dim: 64
    output_dim: 3 # -1, 0, 1
    lr: 1e-3
    seed: 0
    modular_features_N: 100
    input_type: integer # integer, binary, modular_features
    output_file: MobiusFunction_experiment_results.txt

totient:
  args:
    n_samples: 10000
    batch_size: 32
    epochs: 50
    optimizer: adam
    loss: binary_crossentropy
    n_hidden: TODO
    input_dim: TODO
    hidden_dim: TODO
    output_dim: TODO
    lr: 1e-3
    seed: 0
